ARG VERSION=21.1.8
FROM docker.io/library/alpine:latest AS builder
ARG VERSION
RUN apk add --no-cache clang-extra-tools && \
    mkdir -p /output/usr/local/bin /output/usr/lib && \
    cp /usr/lib/llvm21/bin/clangd /output/usr/local/bin/ && \
    cp /usr/lib/llvm21/lib/libclang-cpp.so.* /output/usr/lib/ && \
    cp /usr/lib/llvm21/lib/libLLVM.so.* /output/usr/lib/ && \
    cp /usr/lib/libstdc++.so.* /output/usr/lib/ && \
    cp /usr/lib/libgcc_s.so.1 /output/usr/lib/ && \
    cp /usr/lib/libffi.so.8 /output/usr/lib/ && \
    cp /usr/lib/libz.so.1 /output/usr/lib/ && \
    cp /usr/lib/libzstd.so.1 /output/usr/lib/ && \
    cp /usr/lib/libxml2.so.2 /output/usr/lib/ && \
    cp /usr/lib/liblzma.so.5 /output/usr/lib/ && \
    rm -rf /var/cache/apk/*

FROM docker.io/library/alpine:latest
ARG VERSION
LABEL org.opencontainers.image.title="clangd LSP" \
      org.opencontainers.image.description="C/C++ Language Server" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.source="https://github.com/lsp-client/containers" \
      org.opencontainers.image.licenses="Apache-2.0"

COPY --from=builder /output/usr/local/bin/clangd /usr/local/bin/clangd
COPY --from=builder /output/usr/lib /usr/lib/

WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/clangd"]
