ARG VERSION=v0.21.0
FROM docker.io/library/golang:alpine AS builder
ARG VERSION
ENV CGO_ENABLED=0
RUN go install -ldflags="-s -w" golang.org/x/tools/gopls@${VERSION}

FROM gcr.io/distroless/static-debian12
ARG VERSION
LABEL org.opencontainers.image.title="gopls" \
      org.opencontainers.image.description="Go Language Server" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.source="https://github.com/lsp-client/containers" \
      org.opencontainers.image.licenses="MIT"

COPY --from=builder /go/bin/gopls /usr/local/bin/gopls

WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/gopls"]
